name: Test Suite

on: [push, pull_request]

env:
  RUST_LOG: leveldb=trace,leveldb-sys=trace,leveldb-build-demo=trace
  RUST_TEST_THREADS: 1
  RUST_BACKTRACE: full

jobs:
  test:
    name: Test ${{ matrix.triple }}
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        triple: [
          "x86_64-unknown-linux-gnu",
          "x86_64-unknown-linux-musl",
          "aarch64-unknown-linux-gnu",
          "aarch64-unknown-linux-musl",
        ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - run: cargo install --git https://github.com/rust-embedded/cross --rev e88c7b2
      - run: |
          cross -v test --target ${{ matrix.triple }}
